VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	#BOX
	config.vm.box = "centos/7"
	#config.vm.box_url = "https://url.to.box"
  
	#SHARED FOLDERS
	config.vm.synced_folder ".", "/vagrant"
	#config.vm.synced_folder "/Users/michael/assets/" "/var/www/assets"
  
	#PORT FORWARDING
	config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
	
end
